### PR TITLE
Profile Page

### PR DESCRIPTION
**Pull request by JamesHageman**
- Refactor the broadcast list into it's own component (A `view` and and `update` function)
- Render the profile page with a broadcast list

TODO
- Following and Followers lists in the tab view thing
- We still don't have a broadcast pie or rebroadcasting, but with this refactor we'll have to implement it once and it'll appear on every broadcast list

Sorry for the size, but I wanted to do the refactoring right

### CODE REVIEW

**Comment by georgeutsin** [comment]
Is this a WIP ?

**Comment by JamesHageman** [comment]
No its ready for review. I'll do the TODOs in a follow up or.

On Dec 23, 2016, at 5:39 PM, George Utsin <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this a WIP ?

-

**Review by georgeutsin — APPROVED** [review]
🚀

**Comment by georgeutsin** [comment]
@ethan-hardy its basically christmas so stop driving and get reviewing 🎅🎅🎅

**Comment by ethan-hardy** [comment]
🍼 🍼

**Pull request merged**
